apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
     microservice: {{ .Values.global.name }}
spec:
   type: ClusterIP
   ports:
   - port: 443
     targetPort: 9080
   selector:
      microservice: {{ .Values.global.name }}
